### PR TITLE
add xkcd command

### PR DESCRIPTION
**Pull request by robherley**
image

### CODE REVIEW

**Comment by aavetis** [comment]
no randomize ??

**Comment by robherley** [comment]
okay

**Comment by robherley** [comment]
supports random + embeds for alt text, title and hyperlink

image

**Comment by aavetis** [comment]
i'm pretty sure they have a random endpoint; but this works :) 👍

**Comment by robherley** [comment]
it's hella simple: https://xkcd.com/json.html

**Pull request merged**
